# Name and Description of the Application
name: hybrismarketing
description: Hybris Marketing iBeacon App.

# Version Number for this application
version: 1.0.0+1

# Dart SDK enviornment
environment:
  sdk: ">=2.1.0 <3.0.0"

# Packages used in the app
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  flutter_beacon: ^0.1.1
  flutter_udid: ^1.0.0
  outline_material_icons: ^0.1.0
  gradient_app_bar: ^0.0.1
  intro_slider: ^1.1.7
  shared_preferences: ^0.5.1+1
  bubble_tab_indicator: "^0.1.4"


# Flutter dependency
dev_dependencies:
  flutter_test:
    sdk: flutter

# Material Design Usage, used for the app icons
flutter:
  uses-material-design: true

  assets:
    - assets/
